@startuml
!include theme.plantuml

package "Application frontend"<<Rectangle>> {
    class MyPanel<<Frontend>>
}

package "Digital Cockpit application suite"<<Rectangle>> {
    package "appsuite_media_api_service_core" {
        interface MediaService<<Service>>
        class MediaServiceApi<<Service>>

        MediaServiceApi .> MediaService: is generated based on
    }
    package "appsuite_media_api_common_core" {
        class SourceClient<<Api>>
    }

    package "appsuite_media_api_common_frontend" {
        class PolicyProvider<<Api>>
        interface UserFlowPolicy<<Api>>
    }
}

package "Android "<<Rectangle>> {
    class MediaBrowser<<Android>>
    class MediaBrowserService<<AndroidService>>
}

package "Media source"<<Rectangle>> {
    class AppMediaBrowserService<<Android>> extends MediaBrowserService
}

MyPanel --> SourceClient : connects\nto source
MyPanel --> PolicyProvider : uses\npolicies
PolicyProvider -> UserFlowPolicy
MyPanel -> MediaServiceApi : uses
SourceClient --> MediaBrowser
MediaBrowser -right-> MediaBrowserService
@enduml
