@startuml
!include theme.plantuml
skinparam packageStyle rectangle

title Search

package "Digital Cockpit application suite"<<Rectangle>> {
    component StockSearchFrontend as [Stock Search Frontend]<<Frontend>>
    component SearchUiComponentApi as [Search Ui Component Api]<<Api>>

}

package "Digital Cockpit platform"<<Rectangle>> {
    package "Common APIs" {
        component Coordinate as [Coordinate]<<Api>>
        component TripId as [Trip Id]<<Api>>
        component TripPlan as [Trip Plan]<<Api>>
        component TripPlanError as [Trip Plan Error]<<Api>>

    }
    component NavigationConnectionService as [Navigation Connection Service]<<Service>>
    component NavigationService as [Navigation Service]<<Service>>
    component VehicleLocationService as [Vehicle Location Service]<<Service>>
}

package "NavKit"<<Rectangle>> {
    component FtsResult as [Fts Result]<<Api>>
    component Search as [Search]<<Api>>
}

package "NavKitUI"<<Rectangle>> {
}

StockSearchFrontend -d-> NavigationConnectionService
StockSearchFrontend -d-> NavigationService
StockSearchFrontend -d-> VehicleLocationService

NavigationService -d-> Coordinate
NavigationService -d-> TripId
NavigationService -d-> TripPlan
NavigationService -d-> TripPlanError

VehicleLocationService -d-> Coordinate

SearchUiComponentApi -d-> NavKitUI
SearchUiComponentApi -d-> NavKit
NavKitUI -d-> NavKit



@enduml
