@startuml
!include theme.plantuml
skinparam packageStyle rectangle

title Map Display

package "Digital Cockpit application suite"<<Rectangle>> {
    component StockMapDisplayFrontend as [Stock Map Display Frontend]<<Frontend>>
    component TripRenderManager as [Trip Renderer Manager]<<Frontend>>
}

package "Digital Cockpit platform"<<Rectangle>> {
    package "Core Service APIs"{
        component MapDisplayService as [Map Display Service]<<Service>>
        component MapDisplayConnectionService as [Map Display Connection Service]<<Service>>

    }

    package "Common APIs" {
        component Coordinate as [Coordinate]<<Api>>
        component TripId as [Trip Id]<<Api>>
    }
}

package "NavKit"<<Rectangle>> {
    component TripRenderer as [Trip Renderer]<<Api>>
    component Trip as [Trip]<<Api>>
    component TrafficRenderer as [Traffic Renderer]<<Api>>
    component Map<<API>>
    component MapView<<API>>
    component Route<<API>>
    component Camera<<API>>
}

StockMapDisplayFrontend -d-> MapDisplayConnectionService
StockMapDisplayFrontend -d-> MapDisplayService

StockMapDisplayFrontend -d-> Map
StockMapDisplayFrontend -d-> MapView
StockMapDisplayFrontend -d-> Route
StockMapDisplayFrontend -d-> Camera

StockMapDisplayFrontend -d-> TrafficRenderer

TripRenderManager -d-> TripRenderer
TripRenderManager -d-> Trip

MapDisplayService -d-> Coordinate
MapDisplayService -d-> TripId


@enduml
