@startuml
!include theme.plantuml
skinparam packageStyle rectangle

title VPA domain architecture

package "IndiGO application suite"<<Rectangle>> {
    [VPA2 Frontend]<<Frontend>>
    [VPA1 Frontend]<<Frontend>>
    [VPA Mediator Service]<<Service>>
    [VPA Mediator Settings Service]<<Service>>
}

package "IndiGO platform (VPA adaptations)" {
    [Stock VPA1 Service]<<Service>>
    [Stock VPA2 Service]<<Service>>
}
component [VPA1 Engine] #LightGreen
component [VPA2 Engine] #CornSilk

[VPA1 Frontend] --> [VPA Mediator Service]
[VPA1 Frontend] --> [VPA Mediator Settings Service]
[VPA2 Frontend] --> [VPA Mediator Service]
[VPA2 Frontend] --> [VPA Mediator Settings Service]
[VPA Mediator Service] --> [Stock VPA1 Service]
[VPA Mediator Service] --> [Stock VPA2 Service]
[VPA Mediator Settings Service] --> [Stock VPA1 Service]
[VPA Mediator Settings Service] --> [Stock VPA2 Service]
[Stock VPA1 Service] --> [VPA1 Engine]
[Stock VPA2 Service] --> [VPA2 Engine]

@enduml
