# Copyright © 2020 TomTom NV. All rights reserved.
#
# This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# license agreement between you and TomTom NV. If you are the licensee, you are only permitted
# to use this software in accordance with the terms of your license agreement. If you are
# not the licensee, then you are not authorized to use this software in any manner and should
# immediately return or destroy it.

# Azure pipelines documentation is available at
# https://aka.ms/yaml

variables:
  - template: private-pool-agents/private-cloud-agents.yml@devops-templates
  - template: .azure-templates/variables.yml
  - name: indigoBranchName
    value: indigo-platform-canary
  - group: 'ProductVersion'

trigger: none

resources:
  pipelines:
  - pipeline: indigo_trigger_reset
    project: IVI
    source: IndiGO
    trigger:
      branches:
       include:
         - master
         - releases/*
  containers:
  # Docker containers with run options for private cloud agents and shared Gradle caches.
  - container: docker_indigo_build
    image: 'indigo/build:$(dockerImageVersion)'
    endpoint: 'IVI-Docker'
    options: $(dockerImageDefaultOptions)
  - container: docker_indigo_test
    image: 'indigo/test:$(dockerImageVersion)'
    endpoint: 'IVI-Docker'
    options: $(dockerImageTestingOptions)
  repositories:
  - repository: devops-templates
    type: git
    name: IVI/devops-templates
    ref: refs/tags/1.0.0

pool: 'Private Cloud CPU'

stages:

- stage: PrepareIndigoBranch
  displayName: IndiGO branch preparation
  jobs:
  - job: PrepareIndigoBranch
    displayName: Preparing IndiGO branch
    container: 'docker_indigo_build'
    steps:
    - bash: echo "Resetting trigger"
    - template: .azure-templates/indigo-update.yml
      parameters:
        branch: $(indigoBranchName)

- stage: Build
  displayName: 'Build pipeline'
  dependsOn: PrepareIndigoBranch
  jobs:
  - job: Build
    displayName: Lint & Build
    timeoutInMinutes: '15'
    container: 'docker_indigo_build'
    steps:
    - template: .azure-templates/build.yml
      parameters:
        branch: $(indigoBranchName)
    - template: build/build-cleanup.yml@devops-templates

  - job: UnitTests
    displayName: Unit tests
    container: 'docker_indigo_test'
    timeoutInMinutes: 15
    steps:
    - template: .azure-templates/test-unit.yml
      parameters:
        branch: $(indigoBranchName)
    - template: build/build-cleanup.yml@devops-templates

  - job: IntegrationTests
    displayName: Integration & E2E tests
    container: 'docker_indigo_test'
    timeoutInMinutes: 15
    steps:
    - bash: |
        echo "Instrumented tests here."
      displayName: Run instrumented tests.
    - template: build/build-cleanup.yml@devops-templates

- stage: MergeIndigoBranch
  displayName: IndiGO branch merge
  dependsOn: Build
  jobs:
  - job: MergeIndigoBranch
    displayName: Merge IndiGO canary branch
    container: 'docker_indigo_build'
    steps:
    - template: .azure-templates/merge-feature-branch.yml
      parameters:
        branch: $(indigoBranchName)

- stage: Clean
  displayName: Clean
  dependsOn: MergeIndigoBranch
  condition: always()
  jobs:
  - job: RemoveBranch
    displayName: Remove IndiGO branch
    container: 'docker_indigo_build'
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        set -eux
        git push --delete origin $(indigoBranchName) || true
