# Copyright (c) 2020 - 2021 TomTom N.V. All rights reserved.
#
# This software is the proprietary copyright of TomTom N.V. and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# licensee agreement between you and TomTom. If you are the licensee, you are only permitted
# to use this Software in accordance with the terms of your license agreement. If you are
# not the licensee then you are not authorised to use this software in any manner and should
# immediately return it to TomTom N.V.

# Azure pipelines documentation is available at
# https://aka.ms/yaml

# IndiGO sdk release pipeline

variables:
  - template: private-pool-agents/private-cloud-agents.yml@devops-templates
  - template: .azure-templates/variables.yml
  # Variable groups used below are defined in the project's Pipelines Library.
  - group: 'IviArtifactoryCredentials'
  - group: 'IviNexusCredentials'

resources:
  containers:
  - container: docker_indigo_delivery
    image: 'indigo/delivery:$(dockerImageVersion)'
    endpoint: 'IVI-Docker'
  - container: docker_indigo_build
    image: 'indigo/build:$(dockerImageVersion)'
    endpoint: 'IVI-Docker'
  repositories:
  - repository: indigoqa
    type: git
    name: IVI/indigo-qa
  - repository: devops-templates
    type: git
    name: IVI/devops-templates

trigger:
- none

pool: 'Private Cloud CPU'

stages:
- stage: Publishing
  jobs:
  - job: PublishToNexus
    timeoutInMinutes: 60
    displayName: Publish artifacts to Nexus
    container: docker_indigo_delivery
    steps:
    - template: .azure-templates/publishing-nexus.yml
    - template: build/build-cleanup.yml@devops-templates

- stage: Verification
  dependsOn: Publishing
  jobs:
  - job: DownloadAndVerify
    displayName: Verify SDK contents
    timeoutInMinutes: 30
    container: docker_indigo_build
    steps:
    - template: .azure-templates/downloading-nexus.yml
    - template: gradle/gradle.yml@devops-templates
      parameters:
        cwd: $(Build.SourcesDirectory)/downloads/sdk/examples/sources
        tasks: >-
          assemble
        projectOptions: >-
          -PnexusUsername=$(NEXUS_USERNAME)
          -PnexusPassword=$(NEXUS_PASSWORD)
        displayName: 'Assemble APKs using dependencies from Nexus'
        condition: succeeded()
    - template: build/build-cleanup.yml@devops-templates
