@startuml

participant "Map Display" as MapDisplay #bcdcf5
participant Trips #e5e5e5
participant "Driving assistance" as DrivingAssistance #e5e5e5

MapDisplay -> Trips: planTrip(destination)
Trips -> DrivingAssistance: getCurrentLocation
Trips -> Trips: planTrip(currentLocation, destination)
Trips -> Trips: activateTrip(plannedTrip)
Trips -> MapDisplay: activateTripChanged(trip)
Trips -> Trips: renderTrip(activeTrip)

@enduml
