@startuml
!include theme.plantuml
skinparam packageStyle rectangle

title In-Vehicle Charging

package "Digital Cockpit application suite" {
    [EV Charging Frontend]<<Frontend>>
    [EV Charging Mediator Service]<<Service>>
}

package "Digital Cockpit platform (EV Charging Services)" {
    [Stock EV Charging Service 1]<<Service>>
    [Stock EV Charging Service 2]<<Service>>
}

cloud {
  [eMSP service 1] #LightGreen
}

cloud {
  [eMSP service 2] #CornSilk
}

[EV Charging Frontend] ..> [EV Charging Mediator Service]
[EV Charging Mediator Service] ..> [Stock EV Charging Service 1] 
[EV Charging Mediator Service] ..> [Stock EV Charging Service 2]
[Stock EV Charging Service 1] ..> [eMSP service 1]
[Stock EV Charging Service 2] ..> [eMSP service 2]

@enduml

