# Copyright © 2020 TomTom NV. All rights reserved.
#
# This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# license agreement between you and TomTom NV. If you are the licensee, you are only permitted
# to use this software in accordance with the terms of your license agreement. If you are
# not the licensee, you are not authorized to use this software in any manner and should
# immediately return or destroy it.

parameters:
  artifactoryBaseUrl: https://artifactory.navkit-pipeline.tt3.com/artifactory
  # The API reference subfolder names being used on S3.
  gradlepluginsApiSubFolder: 'tomtom-indigo-gradleplugins-api'
  commsSdkApiSubFolder: 'tomtom-indigo-comms-sdk-api'
  androidToolsApiSubFolder: 'tomtom-android-tools-api'
  indigoPlatformApiSubFolder: 'tomtom-indigo-api'

jobs:
  - job: ApiDocsToS3
    displayName: 'Upload API reference docs to S3'
    timeoutInMinutes: 15
    container: docker_indigo_delivery
    steps:
      - checkout: none
      - template: download/download-and-verify.yml@devops-templates
        parameters:
          downloadUrl: ${{ parameters.artifactoryBaseUrl }}/ivi-maven/com/tomtom/ivi/platform/gradle/api-reference-docs/$(VERSION_PLATFORM)/api-reference-docs-$(VERSION_PLATFORM).tar.gz
          checksumType: 'sha256'
          displayName: Download Gradle Plugins API Reference
      - task: ExtractFiles@1
        displayName: Extract Gradle Plugins API Reference
        inputs:
          archiveFilePatterns: 'downloads/api-reference-docs-$(VERSION_PLATFORM).tar.gz'
          destinationFolder: $(Build.SourcesDirectory)/downloads/${{ parameters.gradlepluginsApiSubFolder }}/html
          cleanDestinationFolder: true
      - template: aws-S3-upload.yml
        parameters:
          apiSubFolder: ${{ parameters.gradlepluginsApiSubFolder }}
          version: $(VERSION_PLATFORM)
      - publish: $(Build.SourcesDirectory)/downloads/${{ parameters.gradlepluginsApiSubFolder }}
        artifact: ${{ parameters.gradlepluginsApiSubFolder }}
        displayName: 'Publish ${{ parameters.gradlepluginsApiSubFolder }} docs as a pipeline artifact'
      - template: download/download-and-verify.yml@devops-templates
        parameters:
          downloadUrl: ${{ parameters.artifactoryBaseUrl }}/ivi-maven/com/tomtom/ivi/sdk/communications/api-reference-docs/$(VERSION_COMMUNICATIONS_SDK)/api-reference-docs-$(VERSION_COMMUNICATIONS_SDK).tar.gz
          checksumType: 'sha256'
          displayName: Download Communications SDK API Reference
      - task: ExtractFiles@1
        displayName: Extract Communications SDK API Reference
        inputs:
          archiveFilePatterns: 'downloads/api-reference-docs-$(VERSION_COMMUNICATIONS_SDK).tar.gz'
          destinationFolder: $(Build.SourcesDirectory)/downloads/${{ parameters.commsSdkApiSubFolder }}/html
          cleanDestinationFolder: true
      - template: aws-S3-upload.yml
        parameters:
          apiSubFolder: ${{ parameters.commsSdkApiSubFolder }}
          version: $(VERSION_COMMUNICATIONS_SDK)
      - publish: $(Build.SourcesDirectory)/downloads/${{ parameters.commsSdkApiSubFolder }}
        artifact: ${{ parameters.commsSdkApiSubFolder }}
        displayName: 'Publish ${{ parameters.commsSdkApiSubFolder }} docs as a pipeline artifact'
      - template: download/download-and-verify.yml@devops-templates
        parameters:
          downloadUrl: ${{ parameters.artifactoryBaseUrl }}/nav-maven-release/com/tomtom/tools/android/api-reference-docs/$(VERSION_TOMTOM_ANDROID_TOOLS)/api-reference-docs-$(VERSION_TOMTOM_ANDROID_TOOLS).tar.gz
          checksumType: 'sha256'
          displayName: Download TomTom Android Tools API Reference
      - task: ExtractFiles@1
        displayName: Extract TomTom Android Tools API Reference
        inputs:
          archiveFilePatterns: 'downloads/api-reference-docs-$(VERSION_TOMTOM_ANDROID_TOOLS).tar.gz'
          destinationFolder: $(Build.SourcesDirectory)/downloads/${{ parameters.androidToolsApiSubFolder }}/html
          cleanDestinationFolder: true
      - template: aws-S3-upload.yml
        parameters:
          apiSubFolder: ${{ parameters.androidToolsApiSubFolder }}
          version: $(VERSION_TOMTOM_ANDROID_TOOLS)
      - publish: $(Build.SourcesDirectory)/downloads/${{ parameters.androidToolsApiSubFolder }}
        artifact: ${{ parameters.androidToolsApiSubFolder }}
        displayName: 'Publish ${{ parameters.androidToolsApiSubFolder }} docs as a pipeline artifact'
      - template: build/build-cleanup.yml@devops-templates

  - job: GenerateIndigoApiDocs
    displayName: 'Generate IndiGO API docs'
    timeoutInMinutes: 60
    container: 'docker_indigo_build'
    dependsOn: ApiDocsToS3
    steps:
      - checkout: indigo
      - bash: |
          cd $(Build.SourcesDirectory)
          git checkout tags/$(VERSION_PLATFORM)
        displayName: 'Checkout IndiGO v$(VERSION_PLATFORM)'
      - template: gradle/gradle.yml@devops-templates
        parameters:
          tasks: >-
            docs
          projectOptions:
            -PiviVersion=$(VERSION_PLATFORM)
            -PandroidToolsExternalApiRefVersion=$(VERSION_TOMTOM_ANDROID_TOOLS)
          displayName: 'Generate IndiGO API docs'
      - publish: $(System.DefaultWorkingDirectory)/build/docs
        artifact: indigo-api-docs
        displayName: 'Publish IndiGO API docs as a pipeline artifact'
      - template: build/build-cleanup.yml@devops-templates

  - job: IndigoApiDocsToS3
    displayName: 'Upload IndiGO API docs to S3'
    timeoutInMinutes: 10
    container: docker_indigo_delivery
    dependsOn: GenerateIndigoApiDocs
    steps:
      - checkout: none
      - template: aws-S3-upload.yml
        parameters:
          artifactName: indigo-api-docs
          apiSubFolder: ${{ parameters.indigoPlatformApiSubFolder }}
          version: $(VERSION_PLATFORM)
      - template: build/build-cleanup.yml@devops-templates
