# Copyright (c) 2020 - 2021 TomTom N.V. All rights reserved.
#
# This software is the proprietary copyright of TomTom N.V. and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# licensee agreement between you and TomTom. If you are the licensee, you are only permitted
# to use this Software in accordance with the terms of your license agreement. If you are
# not the licensee then you are not authorised to use this software in any manner and should
# immediately return it to TomTom N.V.

# Azure pipelines documentation is available at
# https://aka.ms/yaml

parameters:
  # Remote branch to check out
  branch: ''
  # Extra arguments to pass for a lint check, e.g. '--console=plain'
  extraLintParameters: ''

steps:
- template: build-prepare.yml
  parameters:
    branch: ${{parameters.branch}}

- template: gradle/gradle.yml@devops-templates
  parameters:
    tasks: >-
      lint
    projectOptions:
      ${{parameters.extraLintParameters}}
      -PiviVersion=$(product_version)
    displayName: 'Run linters'
    condition: succeeded()

- template: publish/publish-pipeline-artifact.yml@devops-templates
  parameters:
    contents: |
      **/build/reports/lint/report.xml
    displayName: 'Publish lint reports'
    artifact: lint-reports

- template: gradle/gradle.yml@devops-templates
  parameters:
    tasks: >-
      assemble
    projectOptions: >-
      -PiviVersion=$(product_version)
    displayName: 'Assemble APKs'
    condition: succeeded()

- publish: $(System.DefaultWorkingDirectory)/modules/products/exampleapp/build/outputs/apk
  artifact: builds
  displayName: 'Publish APKs as pipeline artifact'
  condition: succeeded()
